film/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [


    path('search/', include('film_search.urls')),
    path('admin/', admin.site.urls),
]

film_search/urls.py
from django.urls import path
from . import views

app_name = 'film_search'

urlpatterns = [

    path('', views.index, name = 'index'),

    path('get/', views.search_get, name = 'search'),
    
    path('play/', views.play, name = 'play'),
    #path('admin/', admin.site.urls),
]

film_search/models.py
from django.db import models

# Create your models here.

film_search/views.py
from django.shortcuts import render

from django.http import HttpResponse, JsonResponse

from croe.film_api import FilmApi

import json



# Create your views here.


def index(request):

    context = {}

    return render(request, 'film_search/index.html',context)


def search_get(request):

    keyword = request.GET.get('keyword')



    search_info = FilmApi().search_detail(keyword)

    count_search_info = 0

    for key, value in search_info['search_detail'].items():

        count_search_info += len(value)
        

    search_info.update({'count': count_search_info})


    context = search_info

    '''
        {'keyword':xx, 'search_detail':{host:{}}}
    '''


    return render(request, 'film_search/search-list.html', context)

def play(request):

    'search/play/?url=http://123ku.com/?m=vod-detail-id-17268.html'

    url = request.GET.get('url')
    
    num = request.GET.get('num')
    print(num)
    
    if num == None:
        
        num = 0
    
    detail = FilmApi().single_detail(url)
    
    detail.update({'show_now':detail['m3u8_list'][int(num)]})

    

    context = detail

    return render(request, 'film_search/play.html', context)




    

film_search/templates/film_search/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>My Cinema</title>
	<link rel="stylesheet" href="{% static 'film_search/css/base.css'%}">
	<link rel="stylesheet" href="{% static 'film_search/css/index.css'%}">
	<script src="{% static 'film_search/js/adjust.js'%}"></script>
</head>
<body>
	<section>
		<div class="wrap">
			<div class="logo">
				<a href="#"></a>
			</div>
			<!-- 搜索 -->
			<div class="search clearfix">
				<form class="clearfix search-form" action="{%url 'film_search:search'%}" method="GET">
					<input type="text" name="keyword" id="" class="search-inp" value="复仇者联盟4">
					<button type="submit" class="search-btn">搜索</button>
				</form>
			</div>
			<!-- 引导 -->
			<div class="guide">
				<a href="./classification.html" class="round">更多火爆影视 --></a>
			</div>
		</div>
	</section>
</body>
<script src="{% static 'film_search/js/carousel.js'%}"></script>
<script>
	window.onload = function () {

		var hrt = document.documentElement.clientHeight; //获取当前可视区域的高度存到hrt的变量里。
		console.log(hrt);
		document.body.style.height = hrt + 'px'
		document.body.style.position = 'absolute'
		// $('body').height(hrt+'px'); //把获取到的高度直接赋值给body
		var searchForm = document.querySelector('.search-form');
		/** @type {HTMLCanvasElement} */
		var searchInp = document.querySelector('.search-inp');
		searchInp.addEventListener('focus', function () {
			searchForm.style.boxShadow = '0 0 6px 1px #fff';
		})
		searchInp.addEventListener('blur', function () {
			searchForm.style.boxShadow = 'none';
		})

		/** @type {HTMLCanvasElement} */
		var guide_vfx = document.querySelector('.guide');
		
		var scale_flag = 1;
		setInterval(function() {
			scale_flag += 0.01
			scale_flag > 1.4 ? scale_flag = 0.4 : false
			guide_vfx.style.transform = `scale(${scale_flag})`
		}, 100/60);
		
	}
</script>
</html>

film_search/templates/film_search/play.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>play</title>
	<link rel="stylesheet" href="{% static 'film_search/css/base.css'%}">
	<link rel="stylesheet" href="{% static 'film_search/css/video.css'%}">
	<script src="{% static 'film_search/js/adjust.js'%}"></script>
	<script src="{% static 'film_search/js/jq.js'%}"></script>
	<script src="https://cdn.jsdelivr.net/hls.js/latest/hls.min.js"></script>
</head>
<body>
	<header class="header clearfix">
		<div class="back"><a href="./index.html">返回</a></div>
		<!-- 搜索 -->
		<div class="search clearfix">
			<form class="clearfix search-form" action="./search-list.html">
				<input type="text" name="" id="" class="search-inp" value="复仇者联盟4">
				<button type="submit" class="search-btn">搜索</button>
			</form>
		</div>
	</header>
	<nav class="head-nav">
		<p class="video-name">{{name}}{{show_now0}}</p>
	</nav>
	<section>
		<div class="video">
	
			<script type="text/javascript" src="{%static 'ckplayer/ckplayer/ckplayer.js'%}"></script>
            <div id="video" style="width:600px;height:400px;"></div>
            <script type="text/javascript">
            	var videoObject = {
            		container: '#video',//“#”代表容器的ID，“.”或“”代表容器的class
            		variable: 'player',//该属性必需设置，值等于下面的new chplayer()的对象
            		flashplayer:false,//如果强制使用flashplayer则设置成true
            		video:{
            		    file:'{{show_now.1}}',//视频地址
            		    type:'video/m3u8'
            		}
            	};
            	var player=new ckplayer(videoObject);
            </script>
		</div>
		<!-- 反馈 -->
		<div class="feedback">
			<div class="feedback-l">
				<span class="feedback-num">10</span>
				顶一下
			</div>
			<div class="feedback-r">
				<span class="feedback-num">10</span>
				报错
			</div>
		</div>
		<!-- 剧集 -->
		<div class="episodes clearfix">
		
		{%for i in m3u8_list%}
			<span><a href="#">{{i.0}}</a></span>
			
        {%endfor%}

		</div>
		
		<!-- 内容简介 -->
		<div class="cont-jianj">
			<p>《<span id="cont_jianj_name">{{name}}</span>》 内容简介</p>
			<div class="cont-text" id="cont_jianj_text">ajdajsdalsjdlajsdlasjdalksjdalkjsdadjasl</div>
		</div>
	</section>
</body>

<script src="{% static 'film_search/js/video.js'%}"></script>
</html>

film_search/templates/film_search/search-list.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=noe">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>查询结果</title>
	<link rel="stylesheet" href="{% static 'film_search/css/base.css'%}">
	<link rel="stylesheet" href="{% static 'film_search/css/search-list.css'%}">
	<script src="{% static 'film_search/js/jq.js'%}"></script>
	<script src="{% static 'film_search/js/underscore.js'%}"></script>
	<script src="{% static 'film_search/js/adjust.js'%}"></script>
</head>
<body>
	<header class="header clearfix">
		<div class="back"><a href="{%url 'film_search:index'%}">返回</a></div>
		<!-- 搜索 -->
		<div class="search clearfix">
				<form class="clearfix search-form" action="{%url 'film_search:search'%}">
					<input type="text" name="keyword" id="" class="search-inp" value="复仇者联盟4">
					<button type="submit" class="search-btn">搜索</button>
				</form>
			</div>
	</header>
	<!-- 查询统计 -->
	<div class="search-stats">
		<div class="header">
			<h3>
				<strong class="search-title">{{keyword}}</strong>
				视频共(
				<strong class="search-num">{{count}}</strong>
				个)
			</h3>
		</div>
		<p class="line"></p>
	</div>
	<!-- 查询结果 -->

	<!--<p class="p"><span class="le">导演：</span><span class="ri">{{info.director|join:','}}</span></p>-->

	
	
	<section class="search-list">
		<ul class="list-wrap">
            {%for key,value in search_detail.items%}
            <li>
                <ul  class="list-wrap">{{key}}</ul>
                {%for info in value%}
            <li>
                <a href="{{i.url}}" class="clearfix">
                    <div class="left-box">
                        <img src="{{info.imgurl}}" alt="">
                    </div>
                    <div class="right-box">
                        <h1 class="video-title">{{info.name}}</h1>
                        <div class="cont">
                            <p class="p">
                                <span class="le">分类：</span>
                                <span class="ri">
                                    {{info.typs}}
                                </span>
                            </p>
                            <!-- <p class="p"><span class="le">类型：</span><span class="ri"><%= v.lei_xing %></span></p> -->
                            <p class="p"><span class="le">演员：</span><span class="ri">{{info.actor|join:','}}</span></p>
                            <p class="p pt"><span class="le">状态：</span><span class="ri">{{info.name_info}}</span></p>
                            <p class="p"><span class="le">时间：</span><span class="ri">{{info.up_date}}</span></p>
                        </div>
                    </div>
                </a>
            </li>
                {% endfor %}
            </li>
            {% endfor %}
		</ul>
	</section>
</body>
<script type="text/html" id="video-temp">
	<% $.each(data, function(k, v){ %>
		<li>
			<a href="./play.html?name=<%= v.name %>" class="clearfix">
				<div class="left-box">
					<img src="<%= v.img_url[0] %>" alt="">
				</div>
				<div class="right-box">
					<h1 class="video-title"><%= v.name %></h1>
					<div class="cont">
						<p class="p"><span class="le">分类：</span>
							<span class="ri">
								<%= v.lei_xing.substring(0,3) %>
							</span>
						</p>
						<!-- <p class="p"><span class="le">类型：</span><span class="ri"><%= v.lei_xing %></span></p> -->
						<p class="p"><span class="le">演员：</span><span class="ri"><%= v.zhu_yan %></span></p>
						<p class="p pt"><span class="le">状态：</span><span class="ri">BD高清</span></p>
						<p class="p"><span class="le">时间：</span><span class="ri"><%= v.update %></span></p>
					</div>
				</div>
			</a>
		</li>
	<% }) %>
</script>
<script src="{% static 'film_search/js/search-list.js'%}"></script>
</html>